spring:
  datasource:
    url: jdbc:mysql://localhost/traderbook_db
    username: traderbook_user
    password: traderbook_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false